### ISSUE TITLE
Assigning precompiled templates to window.nunjucksPrecompiled

### ISSUE THREAD

**Issue by thepechinator** [at0g/nunjucks-loader#12]
Hi again. Happy to see this is still getting updated.

Our team wants to share the same templates we're using in our JS in another project. That way, we don't have to duplicate any of our nunjucks code. It is a Java app and we were planning on using Nashorn to read in our nunjucks-related JS into its Java code and expose nunjucks so we can do something like `nunjucks.render('path/to/template-name.nunj')` within its rendering pipeline.

I ran into a couple of things: 

1) In index.js (https://github.com/at0g/nunjucks-loader/blob/master/index.js#L64), I see you're substituting `window.nunjucksPrecompiled` with `nunjucks.nunjucksPrecompiled`. Why not keep `window.nunjucksPrecompiled` so nunjucks knows we have precompiled templates available if `nunjucks.render()` is used outside the bundle?

2) For the `name` key used in `nunjucks.nunjucksPrecompiled` (https://github.com/at0g/nunjucks-loader/blob/master/index.js#L129), it uses only the name of the nunjucks file and doesn't include the path before it, which can lead to name collisions (so the same name would be used for `templates/hero/default.nunj` and `templates/button/default.nunj`). Am I missing a configuration setting? I think I need to properly set the `this.context` value being used here: https://github.com/at0g/nunjucks-loader/blob/master/index.js#L57.

I can submit a pull request for these, but based on what we're planning to do with nunjucks, I wanted to see whether that's the right approach. Or do you recommend doing something else instead? I could just generate another file with all the precompiled templates on `window.nunjucksPrecompiled`, but it feels like I'm unnecessarily processing our templates twice.

Thanks!

**Comment by at0g** [comment]
Hi Paul,

In regards to point 1, the main goal of this loader is to abstract away the nunjucks environment / runtime details and simply return a callable function. eg.

```
// No nunjucks config - template just renders
var template = require('path/to/template.nunjucks')
var html = template.render({ property: 'value' });
```

The `nunjucksPrecompiled` value is an artefact from the 1.x version which supported node targets (2.x is browser only). Calling `nunjucks.render` is (IMO) defunct - just call the render method of the template itself - this way you get an explicit dependency. eg.

```
// Not supported
// Does 'path/to/template.nunjucks' exist? We'll only find out at run time
nunjucks.render('path/to/template.nunjucks');

// Supported
// Does 'path/to/template.nunjucks' exist? We'll find out at compile time
require('path/to/template.nunjucks').render()
```


Regarding point 2:

`this.context` [comes from webpack and defaults to process.cwd](http://webpack.github.io/docs/configuration.html#context). What [this line](https://github.com/at0g/nunjucks-loader/blob/master/index.js#L57) is doing is setting the name of the template to it's relative path.
If you're getting an overlap of `default.nunj` - can share a reproducible version? 
If you're confident there is infact an error, I would welcome a PR (provided the existing tests pass).

If you're wanting to do node/server-side renders, then the 1.x version of this project is probably a better bet. Although it is feature frozen it works well and is stable.
The 2.x version of nunjucks-loader is currently browser only - I have not had the time to send [this PR](https://github.com/mozilla/nunjucks/issues/507) due to RL commitments - when #507 is resolved I will reinstate UMD support in this loader.

Finally, it may be that the goals of this project do not quite meet your needs / use case. 
If you have not already, you could try [jinja-loader](https://github.com/pierreant-p/jinja-loader) which is more of a bridge to a standard nunjucks loader, where this project is more concerned with creating a standalone callable function.

**Comment by thepechinator** [comment]
I opened a pull request for point 2.

About point 1: I looked at jinja-loader awhile back, and while it does attach stuff to the `window.nunjucksPrecompiled` object, I chose your loader because it definitely felt less awkward to do things like requiring a template and then calling `render` on it. For code we're bundling, it fits our needs well.

The case of needing to populate `window.nunjucksPrecompiled` is for other projects that can't have their code bundled with Webpack, but want to use the same nunjucks instance the loader is using by exposing it outside the bundle. It seems like a waste to have all our templates bundled and processed, but then have to run another process to precompile them in a way that they can be leveraged outside the webpack bundle. In other words, I think we want a cross between your loader and jinja-loader.

I understand your point about abstracting away the nunjucks details, though. I think there are a few things we can do to work around this without modifying the loader's internal code. Thanks for the feedback.
