### ISSUE TITLE
About loader for target=node

### ISSUE THREAD

**Issue by felixsanz** [at0g/nunjucks-loader#29]
Why this doesn't work for target=node? It's a design problem or intended? I would like to use 2.x with node :(

**Comment by at0g** [comment]
The 1.x version will work with node/umd modules - depending on exactly what you need from your templates, it might do the trick.
Since the 2.x releases of nunjucks, I have not been been able to get a umd build to work which is why node support has been dropped in 2.x.

There were blockers with the dependency tree of chokidar (autoloaded by nunjucks for the file system loader, chokidar may become optional with nunjucks in the future) and to a lesser extent, the lack of a runtime only build that works for with node or umd.

Possibly it's doable as a node only target, but I think UMD is the correct approach. 
In the event the nunjucks library becomes UMD compatible, this project will to.

**Comment by felixsanz** [comment]
1.0.7 version gives me this error:

ERROR in ./src/components/page/template.njk
Module build failed: TypeError: Cannot read property 'throwOnUndefined' of undefined
    at Object.module.exports.compile (/home/felixsanz/Desktop/test/node_modules/nunjucks/src/compiler.js:1157:40)
    at Object.module.exports (/home/felixsanz/Desktop/test/node_modules/nunjucks-loader/index.js:52:40)
 @ ./src/components/page/index.js 91:16-41

**Comment by at0g** [comment]
Hmm, that's not good - do you have a 1.x version of nunjucks installed?

`throwOnUndefined` was added in 2.x - maybe your templates depend on newer features?
FYI - old 1.x nunjucks docs: https://github.com/mozilla/nunjucks/tree/9e0b4f0bf614e7b63cdb60c4bdd364d06c6246a5/docs
